[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "MPL-2.0",
    "ISC",
    "BSD-3-Clause",
    "Zlib",
    "CDLA-Permissive-2.0",
    "GPL-3.0"
]

[advisories]
ignore = [
    "RUSTSEC-2025-0057"
]
