[package]
name = "dom-content-extraction"
version = "0.3.14"

description = "Rust implementation of Content extraction via text density paper"
license = "MPL-2.0"
documentation = "https://docs.rs/dom-content-extraction/latest/dom_content_extraction/"
homepage = "https://github.com/oiwn/dom-content-extraction"
repository = "https://github.com/oiwn/dom-content-extraction"
readme = "README.md"
keywords = ["dom-text-density"]
categories = ["data-structures", "web-programming", "text-processing"]
exclude = [
    "tmp/*",
    "benches/*",
    "html/*",
    ".github/*",
    ".gitignore",
    ".tmuxp.yaml",
    ".amc.toml",
    "notes.org"
]

edition = "2024"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[dependencies]
ego-tree = "0.10"
scraper = "0.24"
thiserror = "2"
# binary
clap = { version = "4.5", features = ["derive"], optional = true }
reqwest = { version = "0.12", features = ["blocking"], optional = true }
tempfile = { version = "3.22", optional = true }
url = { version = "2.5", optional = true }
anyhow = { version = "1", optional = true }
unicode-normalization = "0.1"
unicode-segmentation = "1.12"

[dev-dependencies]
criterion = "0.7"
zip = "5"
anyhow = "1"
regex = "1"
rayon = "1"

[[bench]]
name = "simple"
harness = false

[lib]
doctest = false

[[bin]]
name = "dce"
path = "src/main.rs"
required-features = ["cli"]

[features]
default = ["cli"]
cli = [
    "dep:clap",
    "dep:reqwest",
    "dep:tempfile",
    "dep:url",
    "dep:anyhow"
]
