[package]
name = "dom-content-extraction"
version = "0.2.8"

description = "Rust implementation of Content extraction via text density paper"
license = "MPL-2.0"
documentation = "https://github.com/oiwn/dom-content-extraction"
homepage = "https://github.com/oiwn/dom-content-extraction"
repository = "https://github.com/oiwn/dom-content-extraction"
readme = "README.md"
keywords = ["dom-text-density"]
categories = ["data-structures", "web-programming", "text-processing"]
exclude = [
    "tmp/*",
    # "benches/*",
    "html/*",
    ".github/*",
    ".gitignore",
    ".tmuxp.yaml",
    "notes.org"
]

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[dependencies]
ego-tree = "0.6.2"
once_cell = "1.17.1"
scraper = "0.16.0"

[dev-dependencies]
criterion = "0.4"
zip = "0.6"

[[bench]]
name = "simple"
harness = false


