[package]
name = "dom-content-extraction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[dependencies]
ego-tree = "0.6.2"
once_cell = "1.17.1"
scraper = "0.14.0"

[dev-dependencies]
criterion = "0.4"
zip = "0.6"

[[bench]]
name = "simple"
harness = false


