coverage: # https://docs.codecov.com/docs/codecovyml-reference#coverage
  precision: 1 # e.g. 89.1%
  round: down
  range: 80..100 # https://docs.codecov.com/docs/coverage-configuration#section-range
  status: # https://docs.codecov.com/docs/commit-status
    project:
      default:
        threshold: 1% # Avoid false negatives
ignore:
  - "examples"
  - "benches"
comment: # https://docs.codecov.com/docs/pull-request-comments
  # make the comments less noisy
  require_changes: true
